services:
  - type: web
    name: bahasa-anki
    runtime: python
    rootDir: indonesian
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bahasa_anki:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
